### ISSUE TITLE
For paper

### ISSUE THREAD

**Issue by sysun123** [tancheng/VectorCGRA#15]
I am interested in your work, but I can not find a PDF version  in internet now. Can you send a PDF paper to my Email(21212020139@m.fudan.edu.cn) for study? Thank you!!

**Comment by tancheng** [comment]
Here you go: [VecPAC_ICCAD23_camera_ready.pdf](https://github.com/tancheng/VectorCGRA/files/13368550/VecPAC_ICCAD23_camera_ready.pdf). Thanks for the interest. Let me know anything you wanna discuss (e.g., how to deploy it, limititions, potential future research directions).
