### ISSUE TITLE
FU dir hierarchy refinement

### ISSUE THREAD

**Issue by tancheng** [tancheng/VectorCGRA#17]
@rp15
Just a reminder about the unit test fix and dir hierarchy reorg.

**Comment by tancheng** [comment]
1. Many folders have similar names.
2. Refine the description in each file and maybe provide README in FU.
3. How to link to the sub-repo and where they should locate.
4. Put back those failed unit tests.

**Comment by tancheng** [comment]
Hi @rp15, the task 2/3/4 already done?

**Comment by rp15** [comment]
Looking into it!

**Comment by rp15** [comment]
> Looking into it!

2&3 are inlcuded in https://github.com/tancheng/VectorCGRA/pull/63. The RTL for 4 seems to be missing now, the floating-point FUs might have been removed.

**Comment by tancheng** [comment]
Today is this issue's anniversary :-)
