### ISSUE TITLE
About fixed-point  decimal places

### ISSUE THREAD

**Issue by yulilicao** [tancheng/VectorCGRA#18]
Hello, I would like to know the number of decimal places for a fixed number, can you please let me know, thank you

**Comment by tancheng** [comment]
Hi, from the HW perspective, we don't hard-coded that and user is free to determine it by themselves. For the evaluation in our paper, we decided the decimal point based on the max and min value of the evaluated data set.

**Comment by yulilicao** [comment]
Okay, thank you very much for your answer
