### ISSUE TITLE
Questions on CGRA generation and testing.

### ISSUE THREAD

**Issue by ShangkunLi** [tancheng/VectorCGRA#21]
Hi Cheng,

I just walked through your CGRA-Flow using the GUI provided in [the docker image](https://hub.docker.com/r/yuqisun/cgra-flow-openroad). And I have some questions:

1. I tried to deploy [VectorCGRA](https://github.com/tancheng/VectorCGRA) locally. However, there seems to be some problems with the PyMTL3 package. I tried to install pymtl3 using [`pip install pymtl3`](https://github.com/pymtl/pymtl3) or [`pip install git+https://github.com/tancheng/pymtl3.git`](https://github.com/tancheng/VectorCGRA/tree/40858770a221edb369cc03e72f5f133360a896be?tab=readme-ov-file#install-pymtl3-and-python-requirements).  But in both ways, the classes/functions in `pymtl3/stdlib/test_utils` have some little difference with classes/functions in `pymtl3/stdlib/test` from your docker image.

2. In terms of the [Run tests](https://github.com/tancheng/CGRA-Flow/blob/master/mode_dark_light.py#L923) function in your CGRA-Flow GUI, it firstly runs some tests on a determined CGRA coupled with [a specific mapping json file](https://github.com/tancheng/VectorCGRA/blob/40858770a221edb369cc03e72f5f133360a896be/cgra/test/config_fir.json), for the user defined CGRA, it only[ generates the parameterized CGRA](https://github.com/tancheng/VectorCGRA/blob/40858770a221edb369cc03e72f5f133360a896be/cgra/translate/CGRATemplateRTL_test.py). So how to determine whether the mapping result generated by [CGRA-Mapper](https://github.com/tancheng/CGRA-Mapper) is correct?

Thanks for your time and help!

**Comment by tancheng** [comment]
If you checkout to the latest version of VectorCGRA, you need pymtl3 version of `pip install -U git+https://github.com/tancheng/pymtl3.1@yo-struct-list-fix` as shown in the README of VectorCGRA. If you didn't checkout to any version and just use the VectorCGRA within the docker, you don't need to re-install anything IIRC.

Right, that's the issue we wanna fix. The tests are only unit tests and aiming at verification of the existing functionality. We don't have a robust way to guarantee the correctness of the control signals generated from the mapper, as either of the two tools has been developed on its own for a while. Based on our and others experience, it would take a few days to tune the generated control signals to make the RTL simulation run as expected. We are working on DFG-simulator and mapping-verification these days. It would super helpful if you can help contribute on this :-)

**Comment by ShangkunLi** [comment]
Sure, I would be happy to contribute on this functionality extension. Please let me know if you have anything that I can help.
